<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE attributes [<!ELEMENT attributes (attribute*)><!ELEMENT attribute (name, properties?, modes?, uniques?)><!ELEMENT name (#PCDATA)><!ELEMENT properties (property+)><!ELEMENT property (#PCDATA)><!ELEMENT modes (mode+)><!ELEMENT mode (#PCDATA)><!ELEMENT uniques (unique+)><!ELEMENT unique (#PCDATA)><!ATTLIST attribute type (integer|float|string) #REQUIRED><!ATTLIST property name (min|q1|median|q3|max) #REQUIRED>]>
<attributes>
  <attribute type="integer">
    <name>age</name>
    <properties>
      <property name="min">17.0</property>
      <property name="q1">28.0</property>
      <property name="median">37.0</property>
      <property name="q3">48.0</property>
      <property name="max">90.0</property>
    </properties>
    <modes>
      <mode>36</mode>
    </modes>
  </attribute>
  <attribute type="string">
    <name>workclass</name>
    <modes>
      <mode>Private</mode>
    </modes>
    <uniques>
      <unique>Never-worked</unique>
    </uniques>
  </attribute>
  <attribute type="integer">
    <name>fnlwgt</name>
    <properties>
      <property name="min">12285.0</property>
      <property name="q1">117827.0</property>
      <property name="median">178356.0</property>
      <property name="q3">237051.0</property>
      <property name="max">1484705.0</property>
    </properties>
    <modes>
      <mode>123011</mode>
      <mode>203488</mode>
      <mode>164190</mode>
    </modes>
  </attribute>
  <attribute type="string">
    <name>education</name>
    <modes>
      <mode>HS-grad</mode>
    </modes>
    <uniques>
      <unique>Preschool</unique>
    </uniques>
  </attribute>
  <attribute type="integer">
    <name>education-num</name>
    <properties>
      <property name="min">1.0</property>
      <property name="q1">9.0</property>
      <property name="median">10.0</property>
      <property name="q3">12.0</property>
      <property name="max">16.0</property>
    </properties>
    <modes>
      <mode>9</mode>
    </modes>
  </attribute>
  <attribute type="string">
    <name>marital-status</name>
    <modes>
      <mode>Married-civ-spouse</mode>
    </modes>
    <uniques>
      <unique>Married-AF-spouse</unique>
    </uniques>
  </attribute>
  <attribute type="string">
    <name>occupation</name>
    <modes>
      <mode>Prof-specialty</mode>
    </modes>
    <uniques>
      <unique>Armed-Forces</unique>
    </uniques>
  </attribute>
  <attribute type="string">
    <name>relationship</name>
    <modes>
      <mode>Husband</mode>
    </modes>
    <uniques>
      <unique>Other-relative</unique>
    </uniques>
  </attribute>
  <attribute type="string">
    <name>race</name>
    <modes>
      <mode>White</mode>
    </modes>
    <uniques>
      <unique>Other</unique>
    </uniques>
  </attribute>
  <attribute type="string">
    <name>sex</name>
    <modes>
      <mode>Male</mode>
    </modes>
    <uniques>
      <unique>Female</unique>
    </uniques>
  </attribute>
  <attribute type="integer">
    <name>capital-gain</name>
    <properties>
      <property name="min">0.0</property>
      <property name="q1">0.0</property>
      <property name="median">0.0</property>
      <property name="q3">0.0</property>
      <property name="max">99999.0</property>
    </properties>
    <modes>
      <mode>0</mode>
    </modes>
  </attribute>
  <attribute type="integer">
    <name>capital-loss</name>
    <properties>
      <property name="min">0.0</property>
      <property name="q1">0.0</property>
      <property name="median">0.0</property>
      <property name="q3">0.0</property>
      <property name="max">4356.0</property>
    </properties>
    <modes>
      <mode>0</mode>
    </modes>
  </attribute>
  <attribute type="integer">
    <name>hours-per-week</name>
    <properties>
      <property name="min">1.0</property>
      <property name="q1">40.0</property>
      <property name="median">40.0</property>
      <property name="q3">45.0</property>
      <property name="max">99.0</property>
    </properties>
    <modes>
      <mode>40</mode>
    </modes>
  </attribute>
  <attribute type="string">
    <name>native-country</name>
    <modes>
      <mode>United-States</mode>
    </modes>
    <uniques>
      <unique>Holand-Netherlands</unique>
    </uniques>
  </attribute>
  <attribute type="string">
    <name>50k</name>
    <modes>
      <mode>&lt;=50K</mode>
    </modes>
    <uniques>
      <unique>&gt;50K</unique>
    </uniques>
  </attribute>
</attributes>
